# Variable

In [1]:
x=2

In [2]:
print("Variable x =", x)

Variable x = 2


# numeric module

In [3]:
import numpy 

In [4]:
b=numpy.array([-13, 9])

In [5]:
b

array([-13,   9])

# matrix

In [6]:
a=numpy.array([[4, -5], [-2,3]])

In [7]:
print(a)

[[ 4 -5]
 [-2  3]]


# multiply 

In [8]:
numpy.inner(a,b.T)

array([-97,  53])

# solve linear matrix equation

In [13]:
numpy.linalg.solve(a, b)

array([3., 5.])

# inverse

In [14]:
numpy.linalg.inv(a)

array([[1.5, 2.5],
       [1. , 2. ]])

# solve linear matrix equation with inverse

In [15]:
numpy.inner(numpy.linalg.inv(a),b)

array([3., 5.])

# matplotlib

In [16]:
import matplotlib.pyplot as plt